/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelBooking.view;

/**
 * ForgotPasswordView - Forgot password form GUI
 * Displays email, new password fields and reset button
 */
public class ForgotPasswordView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordView.class.getName());

    public ForgotPasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SingUpLabelHeader = new javax.swing.JLabel();
        EmailTextField3 = new javax.swing.JTextField();
        EmailLabel3 = new javax.swing.JLabel();
        BackToLoginButton1 = new javax.swing.JToggleButton();
        RestPasswordButton = new javax.swing.JToggleButton();
        PasswordLabel1 = new javax.swing.JLabel();
        NewPasswordPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField1 = new javax.swing.JLabel();
        ConfirmPasswordPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        SingUpLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SingUpLabelHeader.setForeground(new java.awt.Color(0, 0, 0));
        SingUpLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SingUpLabelHeader.setText("Rest Password");

        EmailTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        EmailTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextField3ActionPerformed(evt);
            }
        });

        EmailLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel3.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel3.setText("Email:");

        BackToLoginButton1.setBackground(new java.awt.Color(102, 102, 102));
        BackToLoginButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToLoginButton1.setForeground(new java.awt.Color(255, 255, 255));
        BackToLoginButton1.setText("Back To Login");
        BackToLoginButton1.setBorder(null);
        BackToLoginButton1.setContentAreaFilled(false);
        BackToLoginButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RestPasswordButton.setBackground(new java.awt.Color(0, 0, 0));
        RestPasswordButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RestPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        RestPasswordButton.setText("Reset Password");
        RestPasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PasswordLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel1.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel1.setText("New Password:");

        NewPasswordPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ConfirmPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordField1.setText("Confirm Password: ");

        ConfirmPasswordPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmailTextField3)
                        .addComponent(EmailLabel3)
                        .addComponent(NewPasswordPasswordField)
                        .addComponent(ConfirmPasswordField1)
                        .addComponent(ConfirmPasswordPasswordField1)
                        .addComponent(RestPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(PasswordLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SingUpLabelHeader)
                        .addGap(18, 18, 18)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(SingUpLabelHeader)
                .addGap(27, 27, 27)
                .addComponent(EmailLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPasswordPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RestPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Getter methods for controller access
    public String getEmailText() {
        return EmailTextField3.getText().trim();
    }

    public String getNewPasswordText() {
        return new String(NewPasswordPasswordField.getPassword());
    }

    public String getConfirmPasswordText() {
        return new String(ConfirmPasswordPasswordField1.getPassword());
    }

    public javax.swing.JToggleButton getResetButton() {
        return RestPasswordButton;
    }

    public javax.swing.JToggleButton getBackButton() {
        return BackToLoginButton1;
    }

    private void EmailTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextField3ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackToLoginButton1;
    private javax.swing.JLabel ConfirmPasswordField1;
    private javax.swing.JPasswordField ConfirmPasswordPasswordField1;
    private javax.swing.JLabel EmailLabel3;
    private javax.swing.JTextField EmailTextField3;
    private javax.swing.JPasswordField NewPasswordPasswordField;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JToggleButton RestPasswordButton;
    private javax.swing.JLabel SingUpLabelHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
