/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelBooking.view;

import javax.swing.JOptionPane;

/**
 * SignUpView - Signup form GUI
 * Displays username, email, password fields and signup button
 */
public class SignUpView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpView.class.getName());

    public SignUpView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SingUpLabelHeader = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        EmailLabel1 = new javax.swing.JLabel();
        BackToLoginButton = new javax.swing.JToggleButton();
        SignUpButton1 = new javax.swing.JToggleButton();
        EmailTextField1 = new javax.swing.JTextField();
        PasswordLabel1 = new javax.swing.JLabel();
        PasswordPasswordField1 = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JLabel();
        ConfirmPasswordPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        SingUpLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SingUpLabelHeader.setForeground(new java.awt.Color(0, 0, 0));
        SingUpLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SingUpLabelHeader.setText("Sign Up");

        UsernameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setText("Username:");

        EmailLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel1.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel1.setText("Email:");

        BackToLoginButton.setBackground(new java.awt.Color(102, 102, 102));
        BackToLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        BackToLoginButton.setText("Back To Login");
        BackToLoginButton.setBorder(null);
        BackToLoginButton.setContentAreaFilled(false);
        BackToLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SignUpButton1.setBackground(new java.awt.Color(0, 0, 0));
        SignUpButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignUpButton1.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton1.setText("Sign Up");
        SignUpButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        EmailTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        PasswordLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel1.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel1.setText("Password:");

        PasswordPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ConfirmPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordField.setText("Confirm Password: ");

        ConfirmPasswordPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(SingUpLabelHeader)
                .addGap(121, 121, 121))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordLabel1)
                        .addComponent(EmailLabel1)
                        .addComponent(UsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(UsernameLabel)
                        .addComponent(EmailTextField1)
                        .addComponent(PasswordPasswordField1)
                        .addComponent(ConfirmPasswordField)
                        .addComponent(ConfirmPasswordPasswordField)
                        .addComponent(SignUpButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(SingUpLabelHeader)
                .addGap(34, 34, 34)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmailLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Getter methods for controller access
    public String getUsernameText() {
        return UsernameTextField.getText().trim();
    }

    public String getEmailText() {
        return EmailTextField1.getText().trim();
    }

    public String getPasswordText() {
        return new String(PasswordPasswordField1.getPassword());
    }

    public String getConfirmPasswordText() {
        return new String(ConfirmPasswordPasswordField.getPassword());
    }

    public javax.swing.JToggleButton getSignUpButton() {
        return SignUpButton1;
    }

    public javax.swing.JToggleButton getBackButton() {
        return BackToLoginButton;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackToLoginButton;
    private javax.swing.JLabel ConfirmPasswordField;
    private javax.swing.JPasswordField ConfirmPasswordPasswordField;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JTextField EmailTextField1;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JPasswordField PasswordPasswordField1;
    private javax.swing.JToggleButton SignUpButton1;
    private javax.swing.JLabel SingUpLabelHeader;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
