/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MovieBooking.view;

/**
 *
 * @author lenovo
 */
public class AuthenticationView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(AuthenticationView.class.getName());

    /**
     * Creates new form AuthenticationView
     */
    public AuthenticationView() {
        initComponents();
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SignUpPage = new javax.swing.JPanel();
        SignUpContentPannel = new javax.swing.JPanel();
        SingUpLabelHeader = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        EmailLabel5 = new javax.swing.JLabel();
        BackToLoginButton = new javax.swing.JToggleButton();
        EmailTextField5 = new javax.swing.JTextField();
        PasswordLabel5 = new javax.swing.JLabel();
        PasswordPasswordField5 = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JLabel();
        ConfirmPasswordPasswordField = new javax.swing.JPasswordField();
        Signupbutton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ForgotPasswordPage = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        SingUpLabelHeader1 = new javax.swing.JLabel();
        EmailTextField6 = new javax.swing.JTextField();
        EmailLabel6 = new javax.swing.JLabel();
        BackToLoginButton1 = new javax.swing.JToggleButton();
        PasswordLabel6 = new javax.swing.JLabel();
        NewPasswordPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField1 = new javax.swing.JLabel();
        ConfirmPasswordPasswordField1 = new javax.swing.JPasswordField();
        ResetPasswordButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LoginPage = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        LoginTextHeader4 = new javax.swing.JLabel();
        EmailTextField4 = new javax.swing.JTextField();
        EmailLabel4 = new javax.swing.JLabel();
        PasswordLabel4 = new javax.swing.JLabel();
        ForgotPasswordButton4 = new javax.swing.JToggleButton();
        PasswordPasswordField4 = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        SignUpPage.setBackground(new java.awt.Color(250, 250, 250));
        SignUpPage.setForeground(new java.awt.Color(204, 255, 255));
        SignUpPage.setLayout(new java.awt.GridBagLayout());

        SignUpContentPannel.setBackground(new java.awt.Color(255, 255, 255));
        SignUpContentPannel
                .setBorder(javax.swing.BorderFactory.createMatteBorder(8, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        SignUpContentPannel.setForeground(new java.awt.Color(102, 102, 102));

        SingUpLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SingUpLabelHeader.setForeground(new java.awt.Color(229, 9, 20));
        SingUpLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SingUpLabelHeader.setText("Sign Up");

        UsernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(229, 9, 20));
        UsernameLabel.setText("Username:");

        EmailLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailLabel5.setForeground(new java.awt.Color(229, 9, 20));
        EmailLabel5.setText("Email:");

        BackToLoginButton.setBackground(new java.awt.Color(102, 102, 102));
        BackToLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackToLoginButton.setForeground(new java.awt.Color(102, 102, 102));
        BackToLoginButton.setText("Back To Login");
        BackToLoginButton.setBorder(null);
        BackToLoginButton.setContentAreaFilled(false);
        BackToLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        EmailTextField5.setBackground(new java.awt.Color(255, 255, 255));
        EmailTextField5.setForeground(new java.awt.Color(0, 0, 0));
        EmailTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PasswordLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel5.setForeground(new java.awt.Color(229, 9, 20));
        PasswordLabel5.setText("Password:");

        PasswordPasswordField5.setBackground(new java.awt.Color(255, 255, 255));
        PasswordPasswordField5.setForeground(new java.awt.Color(0, 0, 0));
        PasswordPasswordField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ConfirmPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(229, 9, 20));
        ConfirmPasswordField.setText("Confirm Password: ");

        ConfirmPasswordPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Signupbutton1.setBackground(new java.awt.Color(229, 9, 20));
        Signupbutton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Signupbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Signupbutton1.setText("Sign Up");
        Signupbutton1.setBorder(null);
        Signupbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signupbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpContentPannelLayout = new javax.swing.GroupLayout(SignUpContentPannel);
        SignUpContentPannel.setLayout(SignUpContentPannelLayout);
        SignUpContentPannelLayout.setHorizontalGroup(
                SignUpContentPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                SignUpContentPannelLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SingUpLabelHeader)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(SignUpContentPannelLayout.createSequentialGroup()
                                .addGroup(SignUpContentPannelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Signupbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(SignUpContentPannelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                        SignUpContentPannelLayout.createSequentialGroup()
                                                                .addGap(47, 47, 47)
                                                                .addGroup(SignUpContentPannelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(EmailLabel5)
                                                                        .addComponent(UsernameLabel)
                                                                        .addComponent(EmailTextField5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                300, Short.MAX_VALUE)
                                                                        .addComponent(UsernameTextField)))
                                                .addGroup(SignUpContentPannelLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(SignUpContentPannelLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(PasswordLabel5)
                                                                .addGroup(SignUpContentPannelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(ConfirmPasswordField)
                                                                        .addComponent(PasswordPasswordField5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                301, Short.MAX_VALUE)
                                                                        .addComponent(ConfirmPasswordPasswordField))))))
                                .addGap(0, 51, Short.MAX_VALUE))
                        .addGroup(SignUpContentPannelLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(BackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        SignUpContentPannelLayout.setVerticalGroup(
                SignUpContentPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SignUpContentPannelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(SingUpLabelHeader)
                                .addGap(40, 40, 40)
                                .addComponent(UsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EmailLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ConfirmPasswordField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConfirmPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Signupbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(42, Short.MAX_VALUE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        SignUpPage.add(SignUpContentPannel, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieBooking/adobe.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(229, 9, 20));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MovieMint");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 244,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        SignUpPage.add(jPanel3, gridBagConstraints);

        getContentPane().add(SignUpPage, "card3");

        ForgotPasswordPage.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPasswordPage.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 1, 1, 1, new java.awt.Color(229, 9, 20)));
        jPanel10.setForeground(new java.awt.Color(102, 102, 102));

        SingUpLabelHeader1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SingUpLabelHeader1.setForeground(new java.awt.Color(229, 9, 20));
        SingUpLabelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SingUpLabelHeader1.setText("Reset Password");

        EmailTextField6.setBackground(new java.awt.Color(255, 255, 255));
        EmailTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        EmailTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextField6ActionPerformed(evt);
            }
        });

        EmailLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailLabel6.setForeground(new java.awt.Color(229, 9, 20));
        EmailLabel6.setText("Email:");

        BackToLoginButton1.setBackground(new java.awt.Color(102, 102, 102));
        BackToLoginButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackToLoginButton1.setForeground(new java.awt.Color(102, 102, 102));
        BackToLoginButton1.setText("Back To Login");
        BackToLoginButton1.setBorder(null);
        BackToLoginButton1.setContentAreaFilled(false);
        BackToLoginButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PasswordLabel6.setBackground(new java.awt.Color(229, 9, 20));
        PasswordLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel6.setForeground(new java.awt.Color(229, 9, 20));
        PasswordLabel6.setText("New Password:");

        NewPasswordPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        NewPasswordPasswordField.setForeground(new java.awt.Color(229, 9, 20));
        NewPasswordPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ConfirmPasswordField1.setBackground(new java.awt.Color(229, 9, 20));
        ConfirmPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ConfirmPasswordField1.setForeground(new java.awt.Color(229, 9, 20));
        ConfirmPasswordField1.setText("Confirm Password: ");

        ConfirmPasswordPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordPasswordField1
                .setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ResetPasswordButton.setBackground(new java.awt.Color(229, 9, 20));
        ResetPasswordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ResetPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetPasswordButton.setText("Reset Password");
        ResetPasswordButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ResetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordLabel6)
                                        .addComponent(EmailLabel6)
                                        .addComponent(ConfirmPasswordField1)
                                        .addGroup(jPanel10Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(EmailTextField6)
                                                .addComponent(NewPasswordPasswordField)
                                                .addComponent(ResetPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        300, Short.MAX_VALUE)
                                                .addComponent(ConfirmPasswordPasswordField1)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(SingUpLabelHeader1)
                                .addContainerGap(204, Short.MAX_VALUE))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(BackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(SingUpLabelHeader1)
                                .addGap(29, 29, 29)
                                .addComponent(EmailLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PasswordLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NewPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ConfirmPasswordField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConfirmPasswordPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(ResetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(70, Short.MAX_VALUE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        ForgotPasswordPage.add(jPanel10, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieBooking/adobe.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(229, 9, 20));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MovieMint");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        ForgotPasswordPage.add(jPanel2, gridBagConstraints);

        getContentPane().add(ForgotPasswordPage, "card4");

        LoginPage.setBackground(new java.awt.Color(255, 255, 255));
        LoginPage.setForeground(new java.awt.Color(51, 51, 51));
        LoginPage.setLayout(new java.awt.GridBagLayout());

        LoginForm.setBackground(new java.awt.Color(255, 255, 255));
        LoginForm.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        LoginForm.setForeground(new java.awt.Color(102, 102, 102));

        LoginTextHeader4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginTextHeader4.setForeground(new java.awt.Color(229, 9, 20));
        LoginTextHeader4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTextHeader4.setText("Login");

        EmailTextField4.setBackground(new java.awt.Color(250, 250, 250));
        EmailTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EmailLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailLabel4.setForeground(new java.awt.Color(229, 9, 20));
        EmailLabel4.setText("Email:");

        PasswordLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel4.setForeground(new java.awt.Color(229, 9, 20));
        PasswordLabel4.setText("Password:");

        ForgotPasswordButton4.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPasswordButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ForgotPasswordButton4.setForeground(new java.awt.Color(102, 102, 102));
        ForgotPasswordButton4.setText("Forgot Password?");
        ForgotPasswordButton4.setBorder(null);
        ForgotPasswordButton4.setContentAreaFilled(false);
        ForgotPasswordButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPasswordButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PasswordPasswordField4.setBackground(new java.awt.Color(255, 255, 255));
        PasswordPasswordField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LoginButton.setBackground(new java.awt.Color(229, 9, 20));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 9, 20), 0));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignUpButton.setBackground(new java.awt.Color(250, 250, 250));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(229, 9, 20));
        SignUpButton.setText("Sign Up");
        SignUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 9, 20)));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
                LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginFormLayout.createSequentialGroup()
                                .addGroup(LoginFormLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EmailTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(LoginFormLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(LoginFormLayout.createSequentialGroup()
                                                        .addGap(139, 139, 139)
                                                        .addComponent(LoginTextHeader4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 117,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(LoginFormLayout.createSequentialGroup()
                                                        .addGap(44, 44, 44)
                                                        .addGroup(LoginFormLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(PasswordPasswordField4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(LoginFormLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(SignUpButton,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                300, Short.MAX_VALUE)
                                                                        .addComponent(LoginButton,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(EmailLabel4)
                                                                        .addComponent(PasswordLabel4)
                                                                        .addComponent(ForgotPasswordButton4,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                111,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addContainerGap(53, Short.MAX_VALUE)));
        LoginFormLayout.setVerticalGroup(
                LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginFormLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(LoginTextHeader4)
                                .addGap(28, 28, 28)
                                .addComponent(EmailLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PasswordLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ForgotPasswordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        LoginPage.add(LoginForm, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieBooking/adobe.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(229, 9, 20));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("MovieMint");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 244,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(14, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        LoginPage.add(jPanel4, gridBagConstraints);

        getContentPane().add(LoginPage, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Signupbutton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Signupbutton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Signupbutton1ActionPerformed

    private void EmailTextField6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EmailTextField6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_EmailTextField6ActionPerformed

    private void ResetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetPasswordButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ResetPasswordButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SignUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Getter methods for controller access
    // Login card getters
    public javax.swing.JTextField getEmailTextField4() {
        return EmailTextField4;
    }

    public javax.swing.JPasswordField getPasswordPasswordField4() {
        return PasswordPasswordField4;
    }

    public javax.swing.JButton getLoginButton4() {
        return LoginButton;
    }

    public javax.swing.JButton getSignUpButton4() {
        return SignUpButton;
    }

    public javax.swing.JToggleButton getForgotPasswordButton4() {
        return ForgotPasswordButton4;
    }

    // SignUp card getters
    public javax.swing.JTextField getUsernameTextField() {
        return UsernameTextField;
    }

    public javax.swing.JTextField getEmailTextField5() {
        return EmailTextField5;
    }

    public javax.swing.JPasswordField getPasswordPasswordField5() {
        return PasswordPasswordField5;
    }

    public javax.swing.JPasswordField getConfirmPasswordPasswordField() {
        return ConfirmPasswordPasswordField;
    }

    public javax.swing.JButton getSignupbutton1() {
        return Signupbutton1;
    }

    public javax.swing.JToggleButton getBackToLoginButton() {
        return BackToLoginButton;
    }

    // Forgot password card getters
    public javax.swing.JTextField getEmailTextField6() {
        return EmailTextField6;
    }

    public javax.swing.JPasswordField getNewPasswordPasswordField() {
        return NewPasswordPasswordField;
    }

    public javax.swing.JPasswordField getConfirmPasswordPasswordField1() {
        return ConfirmPasswordPasswordField1;
    }

    public javax.swing.JButton getResetPasswordButton() {
        return ResetPasswordButton;
    }

    public javax.swing.JToggleButton getBackToLoginButton1() {
        return BackToLoginButton1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackToLoginButton;
    private javax.swing.JToggleButton BackToLoginButton1;
    private javax.swing.JLabel ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordField1;
    private javax.swing.JPasswordField ConfirmPasswordPasswordField;
    private javax.swing.JPasswordField ConfirmPasswordPasswordField1;
    private javax.swing.JLabel EmailLabel4;
    private javax.swing.JLabel EmailLabel5;
    private javax.swing.JLabel EmailLabel6;
    private javax.swing.JTextField EmailTextField4;
    private javax.swing.JTextField EmailTextField5;
    private javax.swing.JTextField EmailTextField6;
    private javax.swing.JToggleButton ForgotPasswordButton4;
    private javax.swing.JPanel ForgotPasswordPage;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JLabel LoginTextHeader4;
    private javax.swing.JPasswordField NewPasswordPasswordField;
    private javax.swing.JLabel PasswordLabel4;
    private javax.swing.JLabel PasswordLabel5;
    private javax.swing.JLabel PasswordLabel6;
    private javax.swing.JPasswordField PasswordPasswordField4;
    private javax.swing.JPasswordField PasswordPasswordField5;
    private javax.swing.JButton ResetPasswordButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel SignUpContentPannel;
    private javax.swing.JPanel SignUpPage;
    private javax.swing.JButton Signupbutton1;
    private javax.swing.JLabel SingUpLabelHeader;
    private javax.swing.JLabel SingUpLabelHeader1;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
