/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MovieBooking.view;

/**
 *
 * @author lenovo
 */
public class MovieBookingView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MovieBookingView.class.getName());

    /**
     * Creates new form MovieBookingView
     */
    public MovieBookingView() {
        initComponents();
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "card2");
        java.awt.CardLayout dashboardCl = (java.awt.CardLayout) AdminDashboards.getLayout();
        dashboardCl.show(AdminDashboards, "card2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserpPannel = new javax.swing.JPanel();
        AdminPannel = new javax.swing.JPanel();
        NavigationBarWithButton = new javax.swing.JPanel();
        AdminDashboards = new javax.swing.JPanel();
        AdminHome = new javax.swing.JPanel();
        AdminMovies = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AdminUser = new javax.swing.JPanel();
        LogoIconAdmin = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        MoviesButton = new javax.swing.JButton();
        UsersButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout UserpPannelLayout = new javax.swing.GroupLayout(UserpPannel);
        UserpPannel.setLayout(UserpPannelLayout);
        UserpPannelLayout.setHorizontalGroup(
            UserpPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        UserpPannelLayout.setVerticalGroup(
            UserpPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        getContentPane().add(UserpPannel, "card3");

        NavigationBarWithButton.setBackground(new java.awt.Color(255, 255, 255));

        AdminDashboards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout AdminHomeLayout = new javax.swing.GroupLayout(AdminHome);
        AdminHome.setLayout(AdminHomeLayout);
        AdminHomeLayout.setHorizontalGroup(
            AdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        AdminHomeLayout.setVerticalGroup(
            AdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        AdminDashboards.add(AdminHome, "card3");

        AdminMovies.setBackground(new java.awt.Color(255, 255, 255));
        AdminMovies.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Director", "Genre", "Language ", "Time", "Rated"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        AddButton.setBackground(new java.awt.Color(229, 9, 20));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("+Add New Movies");
        AddButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        UpdateButton.setBackground(new java.awt.Color(255, 153, 102));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 102));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 9, 20));
        jLabel2.setText("Movie List");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(229, 9, 20)));

        javax.swing.GroupLayout AdminMoviesLayout = new javax.swing.GroupLayout(AdminMovies);
        AdminMovies.setLayout(AdminMoviesLayout);
        AdminMoviesLayout.setHorizontalGroup(
            AdminMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminMoviesLayout.createSequentialGroup()
                .addGroup(AdminMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminMoviesLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminMoviesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(AdminMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AdminMoviesLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminMoviesLayout.setVerticalGroup(
            AdminMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminMoviesLayout.createSequentialGroup()
                .addGroup(AdminMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminMoviesLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminMoviesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 149, Short.MAX_VALUE))
        );

        AdminDashboards.add(AdminMovies, "card2");

        javax.swing.GroupLayout AdminUserLayout = new javax.swing.GroupLayout(AdminUser);
        AdminUser.setLayout(AdminUserLayout);
        AdminUserLayout.setHorizontalGroup(
            AdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        AdminUserLayout.setVerticalGroup(
            AdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        AdminDashboards.add(AdminUser, "card4");

        LogoIconAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogoIconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieBooking/logo.png"))); // NOI18N

        HomeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(0, 0, 0));
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButtonMouseExited(evt);
            }
        });

        MoviesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MoviesButton.setForeground(new java.awt.Color(0, 0, 0));
        MoviesButton.setText("Movies");
        MoviesButton.setBorder(null);
        MoviesButton.setContentAreaFilled(false);
        MoviesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        UsersButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsersButton.setForeground(new java.awt.Color(0, 0, 0));
        UsersButton.setText("Users");
        UsersButton.setBorder(null);
        UsersButton.setContentAreaFilled(false);
        UsersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LogOut");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 9, 20));
        jLabel1.setText("MovieMint");

        javax.swing.GroupLayout NavigationBarWithButtonLayout = new javax.swing.GroupLayout(NavigationBarWithButton);
        NavigationBarWithButton.setLayout(NavigationBarWithButtonLayout);
        NavigationBarWithButtonLayout.setHorizontalGroup(
            NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBarWithButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(NavigationBarWithButtonLayout.createSequentialGroup()
                            .addComponent(LogoIconAdmin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AdminDashboards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavigationBarWithButtonLayout.setVerticalGroup(
            NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBarWithButtonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(NavigationBarWithButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(LogoIconAdmin))
                .addGap(38, 38, 38)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(MoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(UsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(AdminDashboards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AdminPannelLayout = new javax.swing.GroupLayout(AdminPannel);
        AdminPannel.setLayout(AdminPannelLayout);
        AdminPannelLayout.setHorizontalGroup(
            AdminPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavigationBarWithButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AdminPannelLayout.setVerticalGroup(
            AdminPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavigationBarWithButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(AdminPannel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_HomeButtonMouseExited
        if (!isCurrentPage("home")) {
            HomeButton.setText("Home");
        }
    }// GEN-LAST:event_HomeButtonMouseExited

    private void HomeButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_HomeButtonMouseEntered
        if (!HomeButton.getText().contains("underline")) {
            HomeButton.setText(
                    "<html><u>Home</u></html>");
        }
    }// GEN-LAST:event_HomeButtonMouseEntered

    /**
     * Helper method to check if a page is currently active
     *
     * @param page The page name to check ("home", "movies", "users")
     * @return true if the specified page is currently active
     */
    private boolean isCurrentPage(String page) {
        // Check if this is the current active page by checking controller state
        return (page.equals("home") && HomeButton.getText().contains("underline")
                && !MoviesButton.getText().contains("underline") && !UsersButton.getText().contains("underline")) ||
                (page.equals("movies") && MoviesButton.getText().contains("underline")
                        && !HomeButton.getText().contains("underline") && !UsersButton.getText().contains("underline"))
                ||
                (page.equals("users") && UsersButton.getText().contains("underline")
                        && !HomeButton.getText().contains("underline")
                        && !MoviesButton.getText().contains("underline"));
    }

    // Movies button mouse hover handlers
    private void MoviesButtonMouseEntered(java.awt.event.MouseEvent evt) {
        if (!MoviesButton.getText().contains("underline")) {
            MoviesButton.setText("<html><u>Movies</u></html>");
        }
    }

    private void MoviesButtonMouseExited(java.awt.event.MouseEvent evt) {
        // Remove underline effect only if not the current active page
        if (!isCurrentPage("movies")) {
            MoviesButton.setText("Movies");
        }
    }

    // Users button mouse hover handlers
    private void UsersButtonMouseEntered(java.awt.event.MouseEvent evt) {
        if (!UsersButton.getText().contains("underline")) {
            UsersButton.setText("<html><u>Users</u></html>");
        }
    }

    private void UsersButtonMouseExited(java.awt.event.MouseEvent evt) {
        // Remove underline effect only if not the current active page
        if (!isCurrentPage("users")) {
            UsersButton.setText("Users");
        }
    }



    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }



    /**
     * @return
     */

    // Getter methods for controller access
    public javax.swing.JButton getHomeButton() {
        return HomeButton;
    }

    /**
     *
     * @return
     */
    public javax.swing.JButton getMoviesButton() {
        return MoviesButton;
    }

    /**
     *
     * @return
     */
    public javax.swing.JButton getUsersButton() {
        return UsersButton;
    }

    /**
     *
     * @return
     */
    public javax.swing.JButton getLogoutButton() {
        return jButton5;
    }

    /**
     *
     * @return
     */
    public javax.swing.JPanel getContentPanel() {
        return AdminDashboards;
    }

    /**
     *
     * @return
     */
    public javax.swing.JTable getMovieTable() {
        return jTable2;
    }

    /**
     *
     * @return
     */
    public javax.swing.JButton getAddButton() {
        return AddButton;
    }

    /**
     *
     * @return
     */
    public javax.swing.JButton getUpdateButton() {
        return UpdateButton;
    }

    /**
     *
     * @return
     */
    public javax.swing.JButton getDeleteButton() {
        return DeleteButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel AdminDashboards;
    private javax.swing.JPanel AdminHome;
    private javax.swing.JPanel AdminMovies;
    private javax.swing.JPanel AdminPannel;
    private javax.swing.JPanel AdminUser;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel LogoIconAdmin;
    private javax.swing.JButton MoviesButton;
    private javax.swing.JPanel NavigationBarWithButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel UserpPannel;
    private javax.swing.JButton UsersButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
